name: DockerLatest
# requires docker username and password added to secrets
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
      with:
        ref: master
    - name: docker-build
      env:
        PRJ_NAME: your-project-name
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        ls -l
        echo 'Docker Login'
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        cd app
        CAL_VER=$(TZ=America/New_York date +"%y-%m-%d")
        echo 'Docker Build'
        docker build . -t mikeryan56/$PRJ_NAME:$CAL_VER
        docker push mikeryan56/$PRJ_NAME:$CAL_VER
        docker build . -t mikeryan56/$PRJ_NAME:latest
        docker push mikeryan56/$PRJ_NAME:latest

